import localFont from "next/font/local";
import "./globals.css";
import { DataProvider } from "./context/DataContext";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import Main from "@/components/Main";
import Footer from "@/components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DataProvider>
          <div className="flex gap-4 mx-4">
            <div className="w-3/12 hidden md:block">
              <Sidebar />
            </div>
            <div className="md:w-9/12 w-full">
              <Header />
              <main>
                {children}
              </main>
              <Footer />
            </div>
          </div>
        </DataProvider>
      </body>
    </html>
  );
}
